### PR TITLE
LINQ Operators

### PR DESCRIPTION
**Pull request by sguduguntla**
Working on implementing function arguments inside PyStream for map, filter, and split functions

### CODE REVIEW

**Comment by sukritkalra** [comment]
@sguduguntla What's the status of this PR? Can you please push out the code where you're stuck along with an explanation of what isn't working, if any?

**Comment by sguduguntla** [comment]
@sukritkalra Here are the latest changes. Everything works as it should, however, that issue we faced over google meet last time where the operators show the byte version. The reason they do that is because the map_fn being passed into the stream.map(map_fn), is of type |data: &Vec<u8>| -> Vec<u8>, so the MapOperator shows the byte versions of the data. I spent quite a bit of time figuring out a way to fix this issue without changing any major part of your implementations, but didn't want to mess with other parts of the codebase.

**Comment by sukritkalra** [comment]
@sguduguntla This is a non-issue. You're trying to look at the logs from the Rust backend where the messages are `PyObject`s and accurately represented as so. Try adding a `SinkOperator` to your `python/erdos/examples/linq.py` and you should be able to see the correct output. I added the following code:

```python
import erdos
import time

from erdos.operator import Source, Sink
from erdos.streams import WriteStream


class SendOp(Source):
    def __init__(self):
        print("initializing source op")

    def run(self, write_stream: WriteStream):
        count = 0
        while True:
            msg = erdos.Message(erdos.Timestamp(coordinates=[count]), count)
            print("SendOp: sending {msg}".format(msg=msg))
            write_stream.send(msg)
            count += 1
            time.sleep(1)

class ReceiveOp(Sink):
    def __init__(self):
        print("initializing sink op")

    def on_data(self, context, data):
        print("Received {} for time {}".format(data, context.timestamp))



def main():
    """Creates and runs the dataflow graph."""
    count_stream = erdos.connect_source(SendOp,
                                        erdos.operator.OperatorConfig())

    map_stream = count_stream.map(lambda a: a * 2)
    erdos.connect_sink(ReceiveOp, erdos.operator.OperatorConfig(), map_stream)

    erdos.run()


if __name__ == "__main__":
    main()
```

and got the correct logs as follows:

```
2022-01-17T19:52:07.025430Z DEBUG Node 0: Running Operator MapOperator
2022-01-17T19:52:07.026815Z DEBUG Node 1: running operator SourceOperator
2022-01-17T19:52:07.026914Z DEBUG Node 2: Running Operator SinkOperator
SendOp: sending {timestamp: Timestamp::Time([0]), data: 0}
2022-01-17T19:52:07.029804Z DEBUG MapOperator @ Time([0]): received [128, 4, 75, 0, 46] and sent [128, 3, 75, 0, 46]
Received 0 for time Timestamp::Time([0])
SendOp: sending {timestamp: Timestamp::Time([1]), data: 1}
2022-01-17T19:52:08.033390Z DEBUG MapOperator @ Time([1]): received [128, 4, 75, 1, 46] and sent [128, 3, 75, 2, 46]
Received 2 for time Timestamp::Time([1])
SendOp: sending {timestamp: Timestamp::Time([2]), data: 2}
2022-01-17T19:52:09.036115Z DEBUG MapOperator @ Time([2]): received [128, 4, 75, 2, 46] and sent [128, 3, 75, 4, 46]
Received 4 for time Timestamp::Time([2])
SendOp: sending {timestamp: Timestamp::Time([3]), data: 3}
2022-01-17T19:52:10.038775Z DEBUG MapOperator @ Time([3]): received [128, 4, 75, 3, 46] and sent [128, 3, 75, 6, 46]
Received 6 for time Timestamp::Time([3])
SendOp: sending {timestamp: Timestamp::Time([4]), data: 4}
2022-01-17T19:52:11.044516Z DEBUG MapOperator @ Time([4]): received [128, 4, 75, 4, 46] and sent [128, 3, 75, 8, 46]
Received 8 for time Timestamp::Time([4])
SendOp: sending {timestamp: Timestamp::Time([5]), data: 5}
2022-01-17T19:52:12.048817Z DEBUG MapOperator @ Time([5]): received [128, 4, 75, 5, 46] and sent [128, 3, 75, 10, 46]
Received 10 for time Timestamp::Time([5])
SendOp: sending {timestamp: Timestamp::Time([6]), data: 6}
2022-01-17T19:52:13.052858Z DEBUG MapOperator @ Time([6]): received [128, 4, 75, 6, 46] and sent [128, 3, 75, 12, 46]
Received 12 for time Timestamp::Time([6])
```

**Comment by sukritkalra** [comment]
Closing because #223 subsumes this change.

**Pull request closed without merging**
